version: 2

sources:
  - name: staging 
    tables: 
      - name: order
      - name: feedback
      - name: order_item
      - name: payment
      - name: product
      - name: user
      - name: seller
  